### ISSUE TITLE
installation of R package

### ISSUE THREAD

**Issue by edzer** [PondiB/openeocubes#42]
If I run
```
docker run -p 8000:8000  brianpondi/openeocubes
```
after the image is downloaded a large number of R packages are being installed. Why does the image not come with the R packages pre-installed?

**Comment by PondiB** [comment]
> after the image is downloaded a large number of R packages are being installed. Why does the image not come with the R packages pre-installed?

This is because I am using a base [ubuntu:jammy](https://hub.docker.com/_/ubuntu) image and then installing the required package. I could use [rocker:geospatial](https://hub.docker.com/r/rocker/geospatial) but it's heavier and has a lot of packages I don't need.

**Comment by edzer** [comment]
It turned out that my local image was not updated, and didn't include https://github.com/PondiB/openeocubes/commit/527c721faf89c3d95c68f8d3b082febcbf22babb ; pulling it again solved this.

**Comment by PondiB** [comment]
Cool, noted.
